@startuml
title クラウド電子カルテシステム ER図

entity "Clinics" as clinics {
  + id : int(11)
  ---
  clinic_name : varchar(255)
}

entity "Branches" as branches {
  + id : int(11)
  ---
  clinic_id : int(11) [FK clinics.id]
  branch_name : varchar(255)
}

entity "Staffs" as staffs {
  + id : int(11)
  ---
  email : varchar(255)
  staff_name : varchar(255)
  native_name : varchar(255) [nullable]
  password : varchar(255)
  role : varchar(255)
  physician_number : varchar(255) [nullable]
  branch_id : int(11) [FK branches.id]
}

entity "Patients" as patients {
  + id : int(11)
  ---
  clinic_id : int(11) [FK clinics.id]
  patient_number : int(11)
  old_hn : varchar(255)
  name : varchar(255)
  native_name : varchar(255)
  gender : varchar(255)
  passport_number : varchar(255) [nullable]
  national_id : varchar(255) [nullable]
  phone_number : varchar(255) [nullable]
  email : varchar(255) [nullable]
  date_of_birth : date
  notes : text
}

entity "MedicalRecords" as medical_records {
  + id : int(11)
  ---
  visit_status_id : int(11) [FK visit_statuses.id]
  staff_id : int(11) [FK staffs.id]
  patient_id : int(11) [FK patients.id]
  date : date
  problem : text
  medical_notes : text
  prescription : varchar(255)
}

entity "Images" as images {
  + id : int(11)
  ---
  patient_id : int(11) [FK patients.id]
  medical_record_id : int(11) [FK medical_records.id] [nullable]
  image_path : varchar(255)
}

entity "PhysicalInformation" as physical_information {
  + id : int(11)
  ---
  patient_id : int(11) [FK patients.id]
  measurement_datetime : datetime
  height : float
  weight : float
  blood_pressure_systolic : int(11)
  blood_pressure_diastolic : int(11)
  temperature : float
  pulse : int(11)
  spo2 : float
}

entity "VisitStatuses" as visit_statuses {
  + id : int(11)
  ---
  branch_id : int(11) [FK branches.id]
  patient_id : int(11) [FK patients.id]
  status : varchar(255)
  checkin_time : datetime
  status_updated_at : datetime
}

clinics ||--o{ branches
clinics ||--o{ patients
branches ||--o{ visit_statuses
branches ||--o{ staffs
staffs ||--o{ medical_records
visit_statuses ||--|{ medical_records
patients ||--o{ medical_records
patients ||--o{ images
patients ||--o{ physical_information
patients ||--o{ visit_statuses

@enduml
